me when
capJavert/clippy-dictionary pull request #10
Opened 2021-06-26 09:15 UTC by pika04034

idk i added a scratch thingy

2021-06-26 09:31 UTC, capJavert requested changes
No worries :)

Each line of JSON file should end with `,` (comma), except for the last line. Also you are missing one square bracket at the end. You can use https://jsonlint.com to validate contents of `clippy.json` before submitting again.

2021-06-27 10:00 UTC, capJavert approved these changes

2021-06-27 10:01 UTC, merged

2021-06-27 10:01 UTC, capJavert commented
Tnx @pika04034 🤘

2022-07-15 11:50 UTC, KazookiTV commented
ohh so thats where the scratch thing came from